export const GAME_POINTS = {
    POINTS_PER_DAMAGE: 1,
    POINTS_PER_FRAG: 400,
    POINTS_PER_TEAM_WIN: 2000
};

export const STATS = {
    BATTLE: "aHR0cHM6Ly9ub2RlLXNlcnZlcmpzLTUyY2Y0MTgyNmY3MS5oZXJva3VhcHAuY29tL2FwaS9iYXR0bGUtc3RhdHMv",
    STATUS: "aHR0cHM6Ly9ub2RlLXNlcnZlcmpzLTUyY2Y0MTgyNmY3MS5oZXJva3VhcHAuY29tL2FwaS9zdGF0dXM=",
    WS: "bm9kZS1zZXJ2ZXJqcy01MmNmNDE4MjZmNzEuaGVyb2t1YXBwLmNvbQ=="

};

export const CONFIG = {
  DEBOUNCE_DELAY: 500,
  THROTTLE_DELAY: 100,
  SERVER_TIMEOUT: 5000,
  RETRY_ATTEMPTS: 2,
  RETRY_DELAY: 750,
  MIN_RANDOM_DELAY: 10,
  MAX_RANDOM_DELAY: 50,
  UI_UPDATE_DELAY: 50,
  HANGAR_DELAY: 1250,
  SERVER_WARMUP_DELAY: 5000
};

export const CACHE_KEYS = {
  GAME_STATE: 'gameState',
  ACCESS_KEY: 'accessKey'
};

