export const CONFIG = {
  DEBOUNCE_DELAY: 500,
  THROTTLE_DELAY: 100,
  SERVER_TIMEOUT: 5000,
  RETRY_ATTEMPTS: 2,
  RETRY_DELAY: 750,
  MIN_RANDOM_DELAY: 10,
  MAX_RANDOM_DELAY: 50,
  UI_UPDATE_DELAY: 50,
  HANGAR_DELAY: 1250,
  SERVER_WARMUP_DELAY: 5000
};

export const CACHE_KEYS = {
  GAME_STATE: 'gameState',
  ACCESS_KEY: 'accessKey'
};